### ISSUE TITLE
validatePassword always returns true

### ISSUE THREAD

**Issue by mchaver** [A1kmm/hs-bcrypt#8]
Not sure if you are still maintaining this package. I am using GHC 7.10.2 on Ubunut 14.04 LTS. I've tried some of your examples in a program and GHCi. For some reason it looks like `validatePassword` always returns true. 

```haskell
Prelude Crypto.BCrypt BS Data.Maybe> validatePassword (p "$2y$14$xBBZdWgTa8fSU1aPFP5IxeVdUKfT7hUDjmusZEAiNBiYaYEGY/Sh6") (p "badpass")
True
Prelude Crypto.BCrypt BS Data.Maybe> validatePassword (p "$2y$14$xBBZdWgTa8fSU1aPFP5IxeVdUKfT7hUDjmusZEAiNBiYaYEGY/Sh6") (p "mypassword")
True
```

**Comment by A1kmm** [comment]
What version of the memory package (dependency of hs-bcrypt) are you using? Memory 0.8 has a known bug in the 'memConstEqual' function (https://github.com/vincenthz/hs-memory/commit/17af888d3a34c2322a17b8556f45150c16a98fde) that could be the underlying cause (although the signature is unchanged). Latest version of the memory package is 0.10.

I am thinking of raising the lower bound for memory to to be 0.9 because while the signature hasn't changed, memory-0.8 is clearly unusable with hs-bcrypt.

**Comment by A1kmm** [comment]
I have uploaded version 0.0.8 to Hackage, which bumps the lower bound to 0.9 (from pull request #7).

**Comment by mchaver** [comment]
I just tried bumping memory to 0.9 and it worked. Thanks for updating the Hackage.
